### ISSUE TITLE
There is some confusion about the search time. 

### ISSUE THREAD

**Issue by fly2tortoise** [fyqsama/ARNAS#1]
Dear researchers, thanks for your work!

After some experiments, I found that ARNAS takes about 80 hours to design a network architecture in the search space described in the paper, is it normal?   (Is this due to the use of 2-order DARTS ?)
I'm using Pytorch 2.1 and Python 3.11 on single RTX4090.   
Another TNNLS work search was fast.

Very great algorithm.
Thanks for the reply. 
Best wishes.

**Comment by fyqsama** [comment]
Thanks for your interests in our work.
The phenomenon mentioned in terms of ARNAS is normal. This is mainly caused by the 2-order DARTS and the optimization for the architecture parameter for the robust cells. 
Best regards.
